data:
  cpu_dataloader: 4
  data_path: ~/data/ismrm/train_data/artifact
  loading_method: memmap
testing:
  batch_size: 32
  epoch: null
  expname: rtesd_tractometer
  middle_voxel: true
  model_path: ~/data/ismrm/train_data/artifact/result/rtesd_tractometer
  save_count: false
  save_fodf: true
  save_reconstruction: false
